### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by emarkk** [colyseus/colyseus-defold#13]
Everything works fine when target is set to New Local Engine, but when I run the game on my Android device the WebSocket does not work and I get these errors
```
DEBUG:SCRIPT: CONNECTION ERROR!
DEBUG:SCRIPT: /websocket/tools.lua:162: attempt to index upvalue 'mime' (a nil value)
```
I am using `colyseus-defold` with the following dependencies:
```
https://github.com/britzl/defold-websocket/archive/master.zip
https://github.com/britzl/defold-luasocket/archive/0.11.zip
https://github.com/britzl/defold-luasec/archive/master.zip
```

**Comment by britzl** [comment]
It looks like it doesn't build the `mime` native extension (part of `defold-luasocket`)

**Comment by endel** [comment]
That's strange, I've just built for Android and it works fine

**Comment by endel** [comment]
@emarkk have you figured this one out? I see you had some progress [on the forum](https://discuss.colyseus.io/topic/244/questions-about-rooms). Cheers!

**Comment by emarkk** [comment]
Yeah, sorry, I solved it. I think it was due to the Defold Engine which was not up to date.
I updated it and used a debug bundle of the app instead of dmengine.apk and everything worked.

**Comment by endel** [comment]
perfect, going to close this then, thanks!
