### ISSUE TITLE
fossil_delta.lua:559: copy extends past end of input

### ISSUE THREAD

**Issue by selimanac** [colyseus/colyseus-defold#14]
Hi @endel 
I'm trying to update my Defold [example](https://github.com/selimanac/defold-colyseus-tic-tac-toe)  for 10.x. I will update it to schema but it takes time. Meanwhile I want it to work with fossil delta. I read the [Migrating](https://docs.colyseus.io/migrating/0.10/) guide and updated the [server side](https://github.com/selimanac/defold-colyseus-tic-tac-toe/tree/master/server). But I am having an error about the length of the delta. I'm using version 0.10.7 and latest Defold Client. It was working with 0.9.x...
Any idea? 
Thank you.

**Comment by endel** [comment]
Hi @selimanac, thanks for letting me know! This bug was a leftover during my tests to continue supporting Fossil Delta on this client. 

Let me know if you still have any issues!

**Comment by selimanac** [comment]
it is fixed, thank you again
