### ISSUE TITLE
Corona SDK

### ISSUE THREAD

**Issue by gfrisicaro** [colyseus/colyseus-defold#20]
CoronaSDK support, please

**Comment by endel** [comment]
Hi @gfrisicaro,

There are no plans for supporting CoronaSDK. It's a lot of effort for me to maintain and keep all other clients up-to-date. 

I highly encourage you to take the first steps on making the first `colyseus-defold` adaptations to run on CoronaSDK, and I can help you with any of the specifics related to Colyseus later down the road. Basically, a stable open-source WebSocket client would be necessary for the port to be successful.

Cheers

**Comment by gfrisicaro** [comment]
Thank you for your response Endel. What kind of changes to make it compatible with the Corona? can you give me some rough indications? which branch should I start from?

Thank you in advance.
Gianpaolo Frisicaro

Inviato da iPhone

**Comment by endel** [comment]
You're welcome. Here are some of the dependencies that need to be replaced/changed for CoronaSDK. (I might be missing something)

- `websocket.client_async`, from `connection.lua`: https://github.com/colyseus/colyseus-defold/blob/7bf72199f921fa0d850e24605250286845e04526/colyseus/connection.lua#L5
- replace `sys.xxx` calls to the equivalent from Corona (https://github.com/colyseus/colyseus-defold/blob/7bf72199f921fa0d850e24605250286845e04526/colyseus/connection.lua#L20)
- local cache: replace saving/storing data on files using Corona: https://github.com/colyseus/colyseus-defold/blob/7bf72199f921fa0d850e24605250286845e04526/colyseus/storage.lua#L4
- For authentication: replace `http.` calls to an equivalent way to perform web requests on Corona https://github.com/colyseus/colyseus-defold/blob/7bf72199f921fa0d850e24605250286845e04526/colyseus/auth.lua#L94

(/cc @johnveloper, you might be interested in helping out here as well!)

**Comment by gfrisicaro** [comment]
Hi Endel,
I pushed my first commit on the forked repos. Now I can connect to the
server, the msg to join to the chat room was sent but the server doesn't
join the client for some reason. Could you help me?

Thank you
Gianpaolo

Il giorno lun 29 lug 2019 alle ore 21:34 Endel Dreyer <
notifications@github.com> ha scritto:

**Comment by endel** [comment]
https://github.com/colyseus/colyseus/issues/581
