### ISSUE TITLE
Colyseus client for Slua

### ISSUE THREAD

**Issue by chnkd** [colyseus/colyseus-defold#21]
I am trying to create [colyseus-slua](https://github.com/chsqn/colyseus-slua) that merge [slua](https://github.com/pangweiwei/slua) and this repository. slua is for using Lua on Unity. Lot of Chinese developers use it for the hotfix feature on mobile game apps. I check out dependences recursively, and I found that there are two defold-luasec that use in game.project files([subsoap/defold-luasec](https://github.com/subsoap/defold-luasec) and [britzl/defold-luasec](https://github.com/britzl/defold-luasec)). The one is from this repository, the other is from its dependence, [defold-websocket](https://github.com/britzl/defold-websocket). subsoap/defold-luasec and britzl/defold-luasec all fork from [sonountaleban/defold-luasec](https://github.com/sonountaleban/defold-luasec) for using not-yet merged PRs. I think the colyseus-slua I am creating needs to merge all of them. My question is if two defold-luasec at here are fine?

**Comment by endel** [comment]
Hi @chsqn, I believe [britzl/defold-luasec](https://github.com/britzl/defold-luasec) is the only one needed. It already includes the patches from [subsoap/defold-luasec](https://github.com/subsoap/defold-luasec).

This is the first time I've heard of [slua](https://github.com/pangweiwei/slua). As you're using Unity, wouldn't it make sense to use the Unity3d client instead? Cheers

**Comment by chsqn** [comment]
I am not familiar with Defold. It seems like [colyseus-defold/game.project](https://github.com/colyseus/colyseus-defold/blob/master/game.project) should be modified as below:
```
[project]
title = Colyseus Defold Client
version = 0.10
dependencies = https://github.com/britzl/defold-luasocket/archive/0.11.zip https://github.com/britzl/defold-luasocket/archive/0.11.zip https://github.com/britzl/defold-websocket/archive/master.zip
```
I am using [colyseus-unity3d](https://github.com/colyseus/colyseus-unity3d). But the new feature, [SchemaSerializer](https://docs.colyseus.io/state/schema/) require generating code beforehand, it will cause the hot-fix feature (upgrade code after app publish) cannot be implemented.

**Comment by britzl** [comment]
You have luasocket listed twice. I guess you mean one of them should be luasec? Defold-websocket should not depend on master btw, point to a release.
