### ISSUE TITLE
JSON or json

### ISSUE THREAD

**Issue by chsqn** [colyseus/colyseus-defold#22]
I found [JSON API](https://www.defold.com/ref/json) in defold.
In [colyseus/client.lua](https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/client.lua), why is JSON from 3rd-party used at [here](https://github.com/colyseus/colyseus-defold/blob/dc7b331c70c7675df9a10403ac0ff7c050a9116b/colyseus/client.lua#L94)?

**Comment by britzl** [comment]
Defold does only contain json.decode(). There is no json.encode() and I assume that is why there's a third party JSON lib to handle both.

**Comment by endel** [comment]
Thanks for the clarification @britzl, going to close this :)
