### ISSUE TITLE
get_available_rooms

### ISSUE THREAD

**Issue by GreenArrow18** [colyseus/colyseus-defold#24]
Calling this function throws an error:

DEBUG:SCRIPT: /colyseus/client.lua:39: attempt to perform arithmetic on field 'requestId' (a nil value)

Looking at the source, it seems to be referencing requestId, which doesn't appear to be initialized anywhere?

**Comment by endel** [comment]
Thanks for reporting @GreenArrow18, it has been fixed now. Cheers!

**Comment by GreenArrow18** [comment]
Confirming that it works now. Thanks Endel!
