### ISSUE TITLE
duplicate join function

### ISSUE THREAD

**Issue by GreenArrow18** [colyseus/colyseus-defold#25]
In client.lua:
function client:join(room_name, options, callback)
  return self:create_matchmake_request('join', room_name, options or {}, callback)
end

function client:join(room_id, options, callback)
  return self:create_matchmake_request('joinById', room_id, options or {}, callback)
end

The second function should be called joinById instead?

Right now, I am unable to call the join function using the room name because the 2nd function (expecting the room id) overrides the first one.

**Comment by endel** [comment]
Ooops, thanks again @GreenArrow18, I probably didn't pay enough attention during the migration of all clients to the new v0.11 API 😅  It's fixed!

**Comment by GreenArrow18** [comment]
It works now, thanks!
