### ISSUE TITLE
HTML5 Issue

### ISSUE THREAD

**Issue by GreenArrow18** [colyseus/colyseus-defold#26]
When running my client app in the editor, it works ok.

However, when running the HTML5 build, I am having some issues. Here's the output from the console:

DEBUG:SCRIPT: colyseus.serialization.schema.schema:993: bad argument #1 to 'ipairs' (table expected, got nil)
dmloader.js:343 stack traceback:
dmloader.js:343 	[C]: in function 'ipairs'
dmloader.js:343 	colyseus.serialization.schema.schema:993: in function 'reflection_decode'
dmloader.js:343 	colyseus.serialization.schema:34: in function 'handshake'
dmloader.js:343 	colyseus.room:120: in function 'on_message'
dmloader.js:343 	colyseus.room:94: in function 'on_batch_message'
dmloader.js:343 	colyseus.room:50: in function 'listener'
dmloader.js:343 	colyseus.eventemitter:47: in function 'emit'
dmloader.js:343 	colyseus.connection:77: in function <colyseus.connection:76>

1. Using Google Chrome most of the times I get the error above, in a few rare instances I don't get this error though (after force reloading a couple of times).
2. Using Microsoft Edge, sometimes I get the error above, sometimes I don't, but I can get it to work more often compared to Chrome.

Any idea what's wrong here? Looking at my colyseus server logs, it seems the connection is being made successfully, but for some reason on the client side the above errors are showing up (and only on the HTML5 build). From within the Defold editor it works fine all the time though.

Thoughts?

**Comment by endel** [comment]
Hey @GreenArrow18, that's strange, are you sure no other errors are thrown before this? Can you also confirm the version of Colyseus you're using? 

I haven't experienced this issue myself in my HTML5 builds - I'm involved in two Defold projects and haven't seen this issue yet. It may be related to your schema definition, since the error is during HANDSHAKE (where the client-side rebuilds the entire Schema tree).

If you can provide a reproducible scenario it would be great. Cheers!

**Comment by GreenArrow18** [comment]
Now that you mentioned it, I'm actually not using any schemas (yet). So I went ahead and created a dummy schema server-side so that I can initialize it using this.setState() ... and the errors are gone! :)

Not sure why the error only appears on the HTML5 build, but I am assuming my schema server-side was non-existent (null) that's why the error was appearing on the client when it expects a non-null schema(?)

Anyway, it's ok now. Thanks for the fast response as always.
