### ISSUE TITLE
Error Code 6

### ISSUE THREAD

**Issue by GreenArrow18** [colyseus/colyseus-defold#31]
I am trying to upgrade to the latest 0.13 client/server versions. I have made the necessary changes. The client can connect to the server successfully. Client reaches onJoin function on the server, but after that I am getting an error on the client side:
code = 6
error = "chema"

I have a very basic schema defined. What could be the cause of the error?

**Comment by endel** [comment]
Hey @GreenArrow18 👋 

This has been reported a few hours ago on the forums: https://discuss.colyseus.io/topic/359/strange-error-code-12-error-ossil-on-defold-when-joining-server/3

Can you try using the recent `0.13.1` tagged version?

**Comment by GreenArrow18** [comment]
Yes that fixed this particular error. Sorry I missed the new update by a few hours.

Thanks as always endel!
