### ISSUE TITLE
Defold websocket extension

### ISSUE THREAD

**Issue by GreenArrow18** [colyseus/colyseus-defold#35]
Hi @endel, are you still doing tests for the new websocket extension? Last time I tested, I seem to be missing some on_message callbacks from desktop builds. If you have a newer version, I would like to do some tests in my projects again. Thanks!

**Comment by endel** [comment]
Hi @GreenArrow18, thanks for checking in - I've paused it for a while but I'm going to continue soon, so far it seems to be having a strange issue receive messages indeed, which I'm not yet sure where it comes from. 

The example project here on this repo works fine, but the real-world game I have is having some issues receiving either messages or schema callbacks. Feel free to contribute to the `websocket-extension` branch if you'd like to! I'm probably not going to touch it during this weekend so we won't have any conflicts

(btw is the project you're using colyseus online, or are you currently working on it? i remember you from the community from quite some time already! cheers!)

**Comment by GreenArrow18** [comment]
I haven't released any Defold+colyseus game yet. Still working on it, progress has been rather slow as I haven't been able to devote more time to it, and I keep on changing things. Hoping to release soon though, as I need to replace some Flash games I have before the year ends.

From my initial tests with the new websocket extension, I seem to be missing messages when running from the editor only, while html5 build seems ok. I will try to do more tests later. Thanks!

**Comment by GreenArrow18** [comment]
Hi @endel I just saw that you have merged master into the websocket branch already. However, I am getting an error?

```
ERROR:SCRIPT: /colyseus/connection.lua:32: attempt to index global 'websocket' (a nil value)
stack traceback:
	/colyseus/connection.lua:32: in function 'open'
	/colyseus/room.lua:63: in function 'connect'
	/colyseus/client.lua:109: in function 'consume_seat_reservation'
	/colyseus/client.lua:83: in function 'callback'
	/colyseus/client.lua:138: in function </colyseus/client.lua:125>
```

Not sure what's wrong. I have been successful in my previous tests. I am using the websocket branch.

I am upgrading to colyseus 0.14 server and wanted to test with the new client websocket extension as well, since Defold is now recommending to use that instead of the old extensions.

**Comment by britzl** [comment]
@GreenArrow18 are you using: https://github.com/defold/extension-websocket ?

**Comment by GreenArrow18** [comment]
Ahh yes, I forgot to include the new extension! Sorry guys...

Initial tests look good now :)
