### ISSUE TITLE
Serialization issues with MapSchema when clearing and rebuilding the map

### ISSUE THREAD

**Issue by scalemaildev** [colyseus/colyseus-defold#42]
In my game, I have a MapSchema called `visActors` which contains all actors visible to the player. This map is rebuilt on every in-game turn, but the actor ids stay the same. Whenever this map is rebuilt without an actor (i.e the actor died that turn or is out of sight) it causes the following Defold error on the next update:
![Screenshot_20220731_110842](https://user-images.githubusercontent.com/15042849/182041104-ecb6b64b-6e11-422f-9b51-2a51a459b102.png)

I tracked that error down to this section of code:
![Screenshot_20220731_111001](https://user-images.githubusercontent.com/15042849/182041113-5de3c639-338f-4073-b89f-286d5e9beb62.png)

It appears to me that when there's a statechange, any missing entries in the MapSchema throw an error as the class tried to index a nil value for the missing entry.

**Some more code snippets for context:**
Room listening for state updates:
![Screenshot_20220731_110919](https://user-images.githubusercontent.com/15042849/182041172-81850da7-594c-4746-80f7-bc604dfb6e49.png)

Updating the visActors map on the server:

![Screenshot_20220731_195843](https://user-images.githubusercontent.com/15042849/182053627-a1378825-f945-4e53-acd7-836f518970c5.png)

**Comment by endel** [comment]
Hi @scalemaildev, thanks for reporting. Can you provide project/repository where we could clone and reproduce this issue you're experiencing?

**Comment by scalemaildev** [comment]
@endel I will invite you to the two repos you'll need, the server and the pre alpha site. Run the 'develop' branch of both.

**Comment by scalemaildev** [comment]
Since refactoring my server source I'm unable to reproduce this. It may have been an issue with clearing and resetting the Map on each turn-based gamestate update.

If you'd still like to take a look at the commit where the error was occurring let me know.
