### ISSUE TITLE
onAuth failed

### ISSUE THREAD

**Issue by baochungit** [colyseus/colyseus-defold#49]
Hi, I think something just changed and now I've got this error showing in my console

```
DEBUG:SCRIPT: [Colyseus] websocket connected 
DEBUG:SCRIPT: _on_message!	�w�onAuth failed
```

I'm using this dependency: https://github.com/colyseus/colyseus-defold/archive/master.zip
Is there way to get back to the working version? I need to build my app now t.t

**Comment by endel** [comment]
My apologies, you can use the previous stable tag `0.15.3`  (https://github.com/colyseus/colyseus-defold/archive/0.15.3.zip)

**Comment by endel** [comment]
I think this has been fixed on `master` now. Let me know if that works for you @baochungit 🙏

**Comment by baochungit** [comment]
Yes, just checked and and it's working great now. However maybe not related but I see a lot of DEBUG:SCRIPT in console now, like

```
DEBUG:SCRIPT: TRIGGER CHANGE!
DEBUG:SCRIPT: 
{ --[[000001E1475D1630]]
  value = "VI00000503",
  __refid = 17,
  op = 128,
  field = "name"
}
DEBUG:SCRIPT: TRIGGER CHANGE!
DEBUG:SCRIPT: 
{ --[[000001E147594D40]]
  value = "default",
  __refid = 17,
  op = 128,
  field = "avatar"
}
```

**Comment by endel** [comment]
Perfect, thanks for the feedback! Just removed those logs too 🙈
