### ISSUE TITLE
room leave & error events not triggered

### ISSUE THREAD

**Issue by baochungit** [colyseus/colyseus-defold#51]
Hi, it seems the 2 events not been triggered, I added the code bellow to check but never seen any messages in console

````lua
room:on("leave", function(message)
	pprint(message)
end)
room:on("error", function(code, message)
	pprint(code, message)
end)
````

**Comment by endel** [comment]
Thank you for reporting @baochungit, just fixed this on [0.15.8](https://github.com/colyseus/colyseus-defold/releases/tag/0.15.8)
