### ISSUE TITLE
total lost connection when receiving big data

### ISSUE THREAD

**Issue by baochungit** [colyseus/colyseus-defold#52]
Hi, I'm not sure if this issue related to colyeus-defold or extension-websocket but it seems the connection will be lost if server responses big data. In this case, when the connection lost, no `leave` or `error` event fired.

Could you help to check which one related to?

My test is
- client sends request of ranking data
- server responses the data (quite big, 3 tables of 100 records for each one, each record contains player info)
- client lost the connection, nothing responsed

**Comment by endel** [comment]
Thanks for reporting @baochungit, this might be a limitation on the WebSocket client, I'd suggest exposing this data via an HTTP route if you can. 

Recently the Defold SDK had the addition of an HTTP helper you can use: 

```lua
-- client-side
client.http:get("/ranking", function(err, data)
  -- ...
end)
```

```javascript
// server-side
app.get("/ranking", (req, res) => {
  res.json(...);
});
```

**Comment by britzl** [comment]
There is a configurable buffer size in the websocket extension. Add this to game.project to set the buffer size to 100,000 bytes (default is 64 * 1024):

```
[websocket]
buffer_size = 100000
```

**Comment by baochungit** [comment]
Thanks! it works. Why didn't I see this configuration when searching somewhere? :D
