### ISSUE TITLE
Sometimes I got this error

### ISSUE THREAD

**Issue by baochungit** [colyseus/colyseus-defold#57]
```
ERROR:SCRIPT: colyseus/serialization/schema/types/map_schema.lua:76: table index is nil
stack traceback:
  colyseus/serialization/schema/types/map_schema.lua:76: in function delete_by_index
  colyseus/serialization/schema/schema.lua:636: in function decode
  colyseus/serialization/schema.lua:25: in function patch
  colyseus/room.lua:238: in function patch
  colyseus/room.lua:172: in function _on_message
  colyseus/room.lua:69: in function listener
  colyseus/eventemitter.lua:80: in function emit
  colyseus/connection.lua:57: in function <colyseus/connection.lua:40>
```

**Comment by endel** [comment]
Hi @baochungit, thank you for reporting. I believe this one can be fixed in the same way we've fixed with arrays a few weeks ago: https://github.com/colyseus/colyseus-defold/commit/d10df2c108055b642c7000c62b9ee37ddc6dfe46 can you confirm applying this change works as expected? Cheers

**Comment by baochungit** [comment]
Looks like that is it.. I'm still using v0.15.8 :d

**Comment by endel** [comment]
Let's keep this open... The `map_schema.lua` file needs that same patch we've applied on `array_schema.lua`
